### ISSUE TITLE
Upgrade to laravel 11

### ISSUE THREAD

**Issue by AlexVanSteenhoven** [buckaroo-it/BuckarooWrapper_Laravel#7]
Hi,

I was trying to upgrade our project to Laravel 11 with Laravel Shift.
After reviewing the shift and installing the new packages locally I get the following output. 

```
 Problem 1
    - Root composer.json requires buckaroo/laravel 1.0 -> satisfiable by buckaroo/laravel[1.0.0].
    - buckaroo/laravel 1.0.0 requires illuminate/support ^9.0|^10.0 -> found illuminate/support[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.
```

**Comment by ShuCh3n** [comment]
Dear @AlexVanSteenhoven ,

Yes, we are preparing our next release to support Laravel 11. Thanks for bringing this to our attention.

**Comment by ShuCh3n** [comment]
We just release a new version that support the latest Laravel version 
https://github.com/buckaroo-it/BuckarooWrapper_Laravel/releases/tag/1.1.0
